spring.application.name=QuestionGenerator
spring.config.import=optional:file:.env[.properties]
gemini.api.key=${GEMINI_API_KEY}


#curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent"