spring.application.name=QuestionGenerator
spring.config.import=optional:file:.env[.properties]
gemini.api.key=${GEMINI_API_KEY}
server.port=${PORT:8080}

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true